version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2-browsers-legacy
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run lint
      - run:
          command: npm run test:unit
      - run:
          command: npm run build
      - run:
          command: E2E_IPFSD_TYPE=go npm run test:e2e
      - run:
          command: E2E_IPFSD_TYPE=js npm run test:e2e
      - run:
          command: npm run bundlesize
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:latest
        environment:
          DOMAIN: webui.ipfs.io
          BUILD_DIR: build
          CLUSTER_HOST: /dnsaddr/ipfs-websites.collab.ipfscluster.io
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy website to IPFS
          command: |
            pin_name="$DOMAIN build $CIRCLE_BUILD_NUMBER"

            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)

            echo "Website added to IPFS: https://ipfs.io/ipfs/$hash"

            if [ "$CIRCLE_BRANCH" == "master" ] ; then
              dnslink-dnsimple -d $DOMAIN -r _dnslink.dev -l /ipfs/$hash
            fi

            if npx semver "$CIRCLE_TAG"; then
              dnslink-dnsimple -d $DOMAIN -r _dnslink -l /ipfs/$hash
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
          context: ipfs-dns-deploy
          requires:
            - build
