name: Test NodeJS

on:
  workflow_call:
    inputs:
      gh-node-version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.gh-node-version }}
  cancel-in-progress: true

jobs:
  reset-badge:
    runs-on: ubuntu-latest
    steps:
      - name: "Reset ${{ inputs.gh-node-version }} badge"
        if: github.ref == 'refs/heads/main'
        uses: RubbaBoy/BYOB@24f464284c1fd32028524b59607d417a2e36fee7
        with:
          ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
          NAME: "node-${{ inputs.gh-node-version }}"
          LABEL: "${{ inputs.gh-node-version }}"
          STATUS: "Building..."
          COLOR: grey
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-node:
    needs: [reset-badge]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      node-version: ${{ steps.node_version.outputs.version }}
    steps:

    - uses: actions/checkout@v3.5.3

    - name: Use Node.js ${{ inputs.gh-node-version }}
      uses: actions/setup-node@v3.8.0
      with:
        node-version: ${{ inputs.gh-node-version }}

    - name: Remove .npmrc to allow non-strict engines
      run: |
        rm .npmrc

    - name: Get exact nodejs version
      id: node_version
      run: |
        echo "version=$(node --version)" >> $GITHUB_OUTPUT

    - name: Cache bigger downloads
      uses: actions/cache@v3.3.1
      id: cache
      with:
        path: ${{ github.workspace }}/.cache
        key: ${{ runner.os }}-${{ inputs.gh-node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.gh-node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}
          ${{ runner.os }}-${{ inputs.gh-node-version }}

    - name: Install node-pre-gyp
      run: |
        npm install node-pre-gyp --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

    - name: Confirm build works with Node.js ${{ inputs.gh-node-version }} on ${{ matrix.os }}
      run: npm run build

  create-badges:
    needs: [test-node]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Create success badge
        if: ${{ needs.test-node.result == 'success' && github.ref == 'refs/heads/main' }}
        uses: RubbaBoy/BYOB@24f464284c1fd32028524b59607d417a2e36fee7
        with:
          ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
          NAME: "node-${{ inputs.gh-node-version }}"
          LABEL: "${{ needs.test-node.outputs.node-version }}"
          STATUS: ${{needs.test-node.result}}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create failure badge
        if: ${{ needs.test-node.result != 'success' && github.ref == 'refs/heads/main' }}
        uses: RubbaBoy/BYOB@24f464284c1fd32028524b59607d417a2e36fee7
        with:
          ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
          NAME: "node-${{ inputs.gh-node-version }}"
          LABEL: "${{ needs.test-node.outputs.node-version }}"
          STATUS: ${{needs.test-node.result}}
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
