on:
  workflow_call:

jobs:

  test-storybook:
    name: 'test:storybook'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.12.0
      - name: Setup npm@8.1.0
        run: |
          npm install -g npm@8.1.0

      - name: Cache bigger downloads
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

      - name: Run test-storybook:ci
        run: npm run test-storybook:ci

      - name: Generate nyc coverage report
        id: coverage
        run: npx nyc report --reporter=lcov

      - uses: codecov/codecov-action@v3
        with:
          flags: storybook_tests # optional
          name: storybook-coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
