on:
  workflow_call:

jobs:

  test-storybook:
    name: 'test:storybook'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Run test-storybook:ci
        run: npm run test-storybook:ci

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: storybook_tests
          name: storybook-coverage
          files: ./coverage/storybook/coverage-storybook.json
          fail_ci_if_error: false
          verbose: true
